# Generated by Django 4.0.3 on 2022-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardPopulate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(default=0)),
                ('cart', models.ImageField(upload_to='')),
                ('order_improve', models.FloatField()),
                ('revenue', models.IntegerField(default=0)),
                ('dollar', models.ImageField(upload_to='')),
                ('revenue_improve', models.FloatField()),
                ('visitors', models.IntegerField(default=0)),
                ('view', models.ImageField(upload_to='')),
                ('visitors_improved', models.FloatField()),
                ('messages', models.IntegerField(default=0)),
                ('message_icon', models.ImageField(upload_to='')),
                ('message_improve', models.FloatField()),
                ('hello', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Card Populate',
                'verbose_name_plural': 'Card Populate Rows',
            },
        ),
    ]
