# Generated by Django 4.0.3 on 2022-04-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminCRM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpopulate',
            name='hello',
        ),
    ]
