# Generated by Django 4.0.3 on 2022-04-10 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminCRM', '0002_remove_cardpopulate_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpopulate',
            name='cards',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardpopulate',
            name='messages_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardpopulate',
            name='order_text',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardpopulate',
            name='revenue_text',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardpopulate',
            name='visitors_text',
            field=models.CharField(default=11, max_length=90),
            preserve_default=False,
        ),
    ]
