# Generated by Django 4.0.3 on 2022-04-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCRM', '0003_cardpopulate_cards_cardpopulate_messages_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardpopulate',
            old_name='cart',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='cardpopulate',
            old_name='message_improve',
            new_name='percent',
        ),
        migrations.RenameField(
            model_name='cardpopulate',
            old_name='messages_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='dollar',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='message_icon',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='order_improve',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='order_text',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='revenue_improve',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='revenue_text',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='view',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='visitors',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='visitors_improved',
        ),
        migrations.RemoveField(
            model_name='cardpopulate',
            name='visitors_text',
        ),
        migrations.AddField(
            model_name='cardpopulate',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
